version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
      - /var/lib/mysql
    ports:
      - "3307:3306" #mariadb-port
    container_name: mariadb

  frappe:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
    build: .
    ports:
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    stdin_open: true
    tty: true
    links:
      - mariadb
    depends_on:
      - mariadb
    container_name: frappe
